"""Email delivery system for morning videos."""
import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
import config

def send_email_with_video(video_path, recipient_email=None):
    """Send morning video via email."""
    if not recipient_email:
        recipient_email = config.EMAIL_TO

    if not config.EMAIL_FROM or not config.EMAIL_PASSWORD:
        print("❌ Email credentials not configured. Please set EMAIL_FROM and EMAIL_PASSWORD in .env file")
        return False

    try:
        # Create message
        msg = MIMEMultipart()
        msg['From'] = config.EMAIL_FROM
        msg['To'] = recipient_email
        msg['Subject'] = f"Your Morning Motivation - {datetime.now().strftime('%B %d, %Y')}"

        # Email body
        body = f"""
Good morning!

Here's your personalized morning motivation video for {datetime.now().strftime('%A, %B %d, %Y')}.

This video includes:
• AI-generated motivational message
• Your daily agenda
• A Catholic prayer to start your day

Have a blessed and productive day!

---
This email was automatically generated by Awesome Morning
        """.strip()

        msg.attach(MIMEText(body, 'plain'))

        # Attach video file
        if os.path.exists(video_path):
            filename = os.path.basename(video_path)

            with open(video_path, 'rb') as attachment:
                part = MIMEBase('application', 'octet-stream')
                part.set_payload(attachment.read())

            encoders.encode_base64(part)
            part.add_header(
                'Content-Disposition',
                f'attachment; filename= {filename}'
            )

            msg.attach(part)
        else:
            print(f"❌ Video file not found: {video_path}")
            return False

        # Connect to Gmail SMTP server
        print("Connecting to email server...")
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()

        # Login
        print("Logging in...")
        server.login(config.EMAIL_FROM, config.EMAIL_PASSWORD)

        # Send email
        print(f"Sending email to {recipient_email}...")
        text = msg.as_string()
        server.sendmail(config.EMAIL_FROM, recipient_email, text)

        # Close connection
        server.quit()

        print(f"✓ Email sent successfully to {recipient_email}")
        return True

    except smtplib.SMTPAuthenticationError:
        print("❌ Email authentication failed. Please check your credentials.")
        print("   For Gmail, you need to use an App Password, not your regular password.")
        print("   Visit: https://myaccount.google.com/apppasswords")
        return False
    except Exception as e:
        print(f"❌ Error sending email: {e}")
        import traceback
        traceback.print_exc()
        return False

def test_email_config():
    """Test email configuration."""
    if not config.EMAIL_FROM:
        print("❌ EMAIL_FROM not set in .env file")
        return False

    if not config.EMAIL_PASSWORD:
        print("❌ EMAIL_PASSWORD not set in .env file")
        return False

    if not config.EMAIL_TO:
        print("❌ EMAIL_TO not set in .env file")
        return False

    print("✓ Email configuration looks good")
    print(f"  From: {config.EMAIL_FROM}")
    print(f"  To: {config.EMAIL_TO}")
    return True
