"""Email delivery system for morning videos."""
import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
import base64
import config

def send_email_with_video(video_path, recipient_email=None):
    """Send morning video via email using Resend or Gmail."""
    if not recipient_email:
        recipient_email = config.EMAIL_TO

    # Try Resend first (recommended)
    if hasattr(config, 'RESEND_API_KEY') and config.RESEND_API_KEY:
        return send_via_resend(video_path, recipient_email)

    # Fall back to Gmail
    elif hasattr(config, 'EMAIL_FROM') and config.EMAIL_FROM and config.EMAIL_PASSWORD:
        return send_via_gmail(video_path, recipient_email)

    else:
        print("❌ Email not configured. Please set either RESEND_API_KEY or EMAIL_FROM/EMAIL_PASSWORD in .env file")
        return False

def send_via_resend(video_path, recipient_email):
    """Send email using Resend (recommended method)."""
    try:
        import resend
        resend.api_key = config.RESEND_API_KEY

        # Read video file and encode as base64
        if not os.path.exists(video_path):
            print(f"❌ Video file not found: {video_path}")
            return False

        with open(video_path, 'rb') as f:
            video_data = f.read()
            video_base64 = base64.b64encode(video_data).decode()

        filename = os.path.basename(video_path)

        # Send email
        print(f"Sending email via Resend to {recipient_email}...")

        params = {
            "from": config.EMAIL_FROM if hasattr(config, 'EMAIL_FROM') and config.EMAIL_FROM else "Morning Motivation <onboarding@resend.dev>",
            "to": [recipient_email],
            "subject": f"Your Morning Motivation - {datetime.now().strftime('%B %d, %Y')}",
            "html": f"""
                <h2>Good morning! ☀️</h2>
                <p>Here's your personalized morning motivation video for <strong>{datetime.now().strftime('%A, %B %d, %Y')}</strong>.</p>

                <p>This video includes:</p>
                <ul>
                    <li>AI-generated motivational message</li>
                    <li>Your daily agenda</li>
                    <li>A Catholic prayer to start your day</li>
                </ul>

                <p>Have a blessed and productive day!</p>

                <hr>
                <p style="color: #666; font-size: 12px;">This email was automatically generated by Awesome Morning</p>
            """,
            "attachments": [{
                "filename": filename,
                "content": video_base64,
            }]
        }

        email = resend.Emails.send(params)
        print(f"✓ Email sent successfully to {recipient_email} via Resend")
        print(f"  Email ID: {email.get('id', 'N/A')}")
        return True

    except ImportError:
        print("❌ Resend package not installed. Run: pip install resend")
        return False
    except Exception as e:
        print(f"❌ Error sending email via Resend: {e}")
        import traceback
        traceback.print_exc()
        return False

def send_via_gmail(video_path, recipient_email):
    """Send email using Gmail SMTP (fallback method)."""
    try:
        # Create message
        msg = MIMEMultipart()
        msg['From'] = config.EMAIL_FROM
        msg['To'] = recipient_email
        msg['Subject'] = f"Your Morning Motivation - {datetime.now().strftime('%B %d, %Y')}"

        # Email body
        body = f"""
Good morning!

Here's your personalized morning motivation video for {datetime.now().strftime('%A, %B %d, %Y')}.

This video includes:
• AI-generated motivational message
• Your daily agenda
• A Catholic prayer to start your day

Have a blessed and productive day!

---
This email was automatically generated by Awesome Morning
        """.strip()

        msg.attach(MIMEText(body, 'plain'))

        # Attach video file
        if os.path.exists(video_path):
            filename = os.path.basename(video_path)

            with open(video_path, 'rb') as attachment:
                part = MIMEBase('application', 'octet-stream')
                part.set_payload(attachment.read())

            encoders.encode_base64(part)
            part.add_header(
                'Content-Disposition',
                f'attachment; filename= {filename}'
            )

            msg.attach(part)
        else:
            print(f"❌ Video file not found: {video_path}")
            return False

        # Connect to Gmail SMTP server
        print("Connecting to email server...")
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()

        # Login
        print("Logging in...")
        server.login(config.EMAIL_FROM, config.EMAIL_PASSWORD)

        # Send email
        print(f"Sending email to {recipient_email}...")
        text = msg.as_string()
        server.sendmail(config.EMAIL_FROM, recipient_email, text)

        # Close connection
        server.quit()

        print(f"✓ Email sent successfully to {recipient_email}")
        return True

    except smtplib.SMTPAuthenticationError:
        print("❌ Email authentication failed. Please check your credentials.")
        print("   For Gmail, you need to use an App Password, not your regular password.")
        print("   Visit: https://myaccount.google.com/apppasswords")
        return False
    except Exception as e:
        print(f"❌ Error sending email: {e}")
        import traceback
        traceback.print_exc()
        return False

def test_email_config():
    """Test email configuration."""
    print("Checking email configuration...\n")

    # Check for Resend (recommended)
    if hasattr(config, 'RESEND_API_KEY') and config.RESEND_API_KEY:
        print("✓ Resend API key configured (RECOMMENDED)")
        print(f"  Provider: Resend")
        if hasattr(config, 'EMAIL_FROM') and config.EMAIL_FROM:
            print(f"  From: {config.EMAIL_FROM}")
        else:
            print(f"  From: onboarding@resend.dev (default)")
        print(f"  To: {config.EMAIL_TO if hasattr(config, 'EMAIL_TO') else 'Not set'}")
        return True

    # Check for Gmail
    elif hasattr(config, 'EMAIL_FROM') and config.EMAIL_FROM and hasattr(config, 'EMAIL_PASSWORD') and config.EMAIL_PASSWORD:
        print("✓ Gmail SMTP configured")
        print(f"  Provider: Gmail")
        print(f"  From: {config.EMAIL_FROM}")
        print(f"  To: {config.EMAIL_TO if hasattr(config, 'EMAIL_TO') else 'Not set'}")
        print("\n⚠️  Note: Resend is recommended for better deliverability")
        return True

    else:
        print("❌ No email provider configured")
        print("\nPlease set ONE of the following in your .env file:")
        print("\nOption 1 (RECOMMENDED): Resend")
        print("  RESEND_API_KEY=re_...")
        print("  EMAIL_FROM=your-email@yourdomain.com (optional)")
        print("  EMAIL_TO=cmraad1@gmail.com")
        print("\nOption 2: Gmail")
        print("  EMAIL_FROM=your-gmail@gmail.com")
        print("  EMAIL_PASSWORD=your-app-password")
        print("  EMAIL_TO=cmraad1@gmail.com")
        return False
